version: '3.8'

services:
  web:
    build: .
    container_name: imap_vinted_bot
    environment:
      - ENV_FILE=.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python -m app